import fs from 'node:fs';
import vm from 'node:vm';
const file=new URL('./index.html',import.meta.url);const html=fs.readFileSync(file,'utf8');
const tests=[];const check=(name,ok)=>tests.push([name,!!ok]);
check('single-file static build',html.includes('<canvas id="canvas">')&&html.includes("(()=>{'use strict';"));
check('certified joystick acquisition',html.includes('adoptPad(e)')&&html.includes('REACQUIRE_DWELL=75')&&html.includes('REACQUIRE_SCALE=1.18'));
check('pointer release and cancellation stop movement',html.includes("addEventListener('pointerup'")&&html.includes("addEventListener('pointercancel'")&&html.includes('padReset()'));
check('simultaneous movement and fire ownership',html.includes('padPointer')&&html.includes('firePointer')&&html.includes("enqueue('fireDown')"));
check('bounded frame delta',html.includes("Math.min(.033,(ts-last)/1000"));
check('central input and audio queues',html.includes('const inputQueue=[],audioQueue=[]')&&html.includes('processInput()')&&html.includes('processAudio()'));
check('eight tactical weapons',Object.keys({pistol:1,shotgun:1,smg:1,rifle:1,magnum:1,lmg:1,flamer:1,launcher:1}).every(k=>html.includes(`${k}:{name:`)));
check('six sector authored arc',html.includes("['RECEIVING'")&&html.includes("['SURFACE SHAFT'")&&html.includes('state.sector>6'));
check('nine minute sector clock and boss gate',html.includes('Math.max(0,540-state.time)')&&html.includes('state.time>=510')&&html.includes('spawnBoss()'));
check('manual and empty reload paths',html.includes("e.type==='reload'")&&html.includes("queueSound('empty');startReload()"));
check('staged reload audio',html.includes("queueSound('magOut')")&&html.includes("queueSound('magIn')")&&html.includes("'reloadEnd'"));
check('near-death pulse shake',html.includes('ratio<.3')&&html.includes("queueSound('heart')")&&html.includes('pulseShake'));
check('darkness uses isolated compositing mask',html.includes("shadeCanvas=document.createElement('canvas')")&&html.includes("shade.globalCompositeOperation='destination-out'")&&html.includes('ctx.drawImage(shadeCanvas,0,0,W,H)'));
check('readable ambient light floor',html.includes("shade.fillStyle='rgba(0,0,0,.46)'")&&html.includes('r=175+state.mods.night')&&html.includes("ratio<.3?red:.45"));
check('upgrade decision system',html.includes('const UPGRADES=[')&&html.includes('offerThree(UPGRADES)')&&html.includes('applyUpgrade'));
check('choice cards commit on direct pointer release',html.includes("button.addEventListener('pointerup',commit)")&&html.includes("wireChoice(b,'upgrade',u[0])")&&html.includes("wireChoice(b,'arsenal',id)"));
check('mobile hardening preserves button taps',html.includes("if(e.target.closest?.('button'))return")&&html.includes("if(e.cancelable)e.preventDefault()"));
check('upgrade choice exits overlay',html.includes("ui.choice.classList.add('hidden');state.mode='playing'"));
check('versioned checkpoint persistence',html.includes("SAVE_KEY='lastShiftBlackoutSave'")&&html.includes('version===2')&&html.includes('snapshot()'));
check('failed sectors restore true checkpoint',html.includes('checkpointRun')&&html.includes("e.type==='retry'){continueRun()")&&html.includes("save('meta')"));
check('arsenal choice is resumable',html.includes('pendingArsenal')&&html.includes('state.pendingArsenal=true;save();openArsenal()'));
check('lifecycle pause and audio recovery',html.includes("document.addEventListener('visibilitychange'")&&html.includes("audio.status='suspended'"));
check('mobile browser hardening',html.includes('-webkit-touch-callout:none')&&html.includes("addEventListener('contextmenu'")&&html.includes('touch-action:none'));
check('global browser zoom is suppressed',html.includes('touch-action:manipulation;-ms-touch-action:manipulation')&&html.includes("game.addEventListener('dblclick'")&&html.includes("['gesturestart','gesturechange','gestureend']"));
check('rapid nearby taps suppress smart zoom',html.includes("game.addEventListener('touchend'")&&html.includes('lastTouchEnd.time<360')&&html.includes('close'));
check('viewport scale change pauses combat',html.includes('window.visualViewport')&&html.includes('Math.abs(next-viewportScale)>.01)enterPause()'));
check('fire near-miss forgiveness',html.includes('function inFireForgiveness')&&html.includes('m=20')&&html.includes('pressFire(e,ui.controls)'));
check('finite auto lock acquisition',html.includes('LOCK_RANGE=360')&&html.includes('d<=LOCK_RANGE')&&html.includes('function updateLockTarget()'));
check('sticky lock hysteresis',html.includes('LOCK_SWITCH_RATIO=.72')&&html.includes('bestDist<currentDist*LOCK_SWITCH_RATIO'));
check('lock overrides aim but not movement',html.includes('p.dir=Math.atan2(ny,nx)')&&html.includes('p.dir=Math.atan2(current.y-p.y,current.x-p.x)'));
check('first and held shots refresh lock',html.includes('function shoot(){if(state.mode!==\'playing\')return;updateLockTarget()')&&html.includes('updateLockTarget();state.lockPulse'));
check('lock feedback and invalidation',html.includes('e===state.lockTarget')&&html.includes('state.lockPulse*6')&&html.includes('if(state.lockTarget===e)clearLock()'));
check('lock controls are explained in game',html.includes('aim snaps to a nearby threat')&&html.includes('GOLD BRACKETS'));
check('one-screen overlays preserve playfield',html.includes('choiceOverlay')&&html.includes('pauseOverlay')&&html.includes('position:absolute;inset:0'));
const script=html.match(/<script>([\s\S]*?)<\/script>/)?.[1];try{new vm.Script(script);check('javascript parses',true)}catch(e){console.error(e);check('javascript parses',false)}
try{const clearFn=script.match(/(function clearLock\(\)\{[^}]*\})/)?.[1],lockFn=script.match(/(function updateLockTarget\(\)\{[\s\S]*?\})\nfunction shoot/)?.[1],sandbox={state:{mode:'playing',player:{x:0,y:0,dir:0},enemies:[],lockTarget:null,lockPulse:0}};vm.createContext(sandbox);new vm.Script(`const LOCK_RANGE=360,LOCK_SWITCH_RATIO=.72;${clearFn};${lockFn};this.lock=updateLockTarget`).runInContext(sandbox);const a={x:100,y:0,dead:false},b={x:130,y:0,dead:false};sandbox.state.enemies=[a,b];sandbox.lock();const choosesNearest=sandbox.state.lockTarget===a;b.x=80;sandbox.lock();const resistsChatter=sandbox.state.lockTarget===a;b.x=0;b.y=70;sandbox.lock();const switchesDecisively=sandbox.state.lockTarget===b&&Math.abs(sandbox.state.player.dir-Math.PI/2)<1e-9;a.x=400;b.y=361;sandbox.lock();const dropsOutOfRange=sandbox.state.lockTarget===null;check('auto lock behavior contract',choosesNearest&&resistsChatter&&switchesDecisively&&dropsOutOfRange)}catch(e){console.error(e);check('auto lock behavior contract',false)}
let failed=0;for(const [name,ok] of tests){console.log(`${ok?'PASS':'FAIL'}  ${name}`);if(!ok)failed++}console.log(`\n${tests.length-failed}/${tests.length} checks passed`);process.exitCode=failed?1:0;
